# Generated by Django 6.0.4 on 2026-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0002_recruitermodel_seekermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('Recruiter', 'Recruiter'), ('Seeker', 'Seeker')], default='Seeker', max_length=20),
        ),
    ]
