# Generated by Django 6.0.5 on 2026-05-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0004_category_skillset_jobpost_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skill_set',
            field=models.ManyToManyField(related_name='skill_set', to='app_base.skillset'),
        ),
    ]
