# Generated by Django 6.0.5 on 2026-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0005_alter_jobpost_description_alter_jobpost_skill_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'APPLIED'), ('SELECTED', 'SELECTED'), ('WAITING', 'WAITING')], default='APPLIED', max_length=20),
        ),
    ]
