# Generated by Django 6.0.4 on 2026-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0007_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('SELECTED', 'SELECTED'), ('APPLIED', 'APPLIED'), ('WAITING', 'WAITING')], default='APPLIED', max_length=20),
        ),
    ]
